
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CONJUNCTION EQUIVALENCE LPAREN RPAREN VARIABLE\n    formula : atom\n    formula : conjunction \n    formula : equivalence\n    \n    atom : VARIABLE\n    \n    conjunction : LPAREN formula CONJUNCTION formula RPAREN\n    \n    equivalence : LPAREN formula EQUIVALENCE formula RPAREN\n    '
    
_lr_action_items = {'VARIABLE':([0,6,8,9,],[5,5,5,5,]),'LPAREN':([0,6,8,9,],[6,6,6,6,]),'$end':([1,2,3,4,5,12,13,],[0,-1,-2,-3,-4,-5,-6,]),'CONJUNCTION':([2,3,4,5,7,12,13,],[-1,-2,-3,-4,8,-5,-6,]),'EQUIVALENCE':([2,3,4,5,7,12,13,],[-1,-2,-3,-4,9,-5,-6,]),'RPAREN':([2,3,4,5,10,11,12,13,],[-1,-2,-3,-4,12,13,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,6,8,9,],[1,7,10,11,]),'atom':([0,6,8,9,],[2,2,2,2,]),'conjunction':([0,6,8,9,],[3,3,3,3,]),'equivalence':([0,6,8,9,],[4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> atom','formula',1,'p_formula','odgarbacza.py',73),
  ('formula -> conjunction','formula',1,'p_formula','odgarbacza.py',74),
  ('formula -> equivalence','formula',1,'p_formula','odgarbacza.py',75),
  ('atom -> VARIABLE','atom',1,'p_atom','odgarbacza.py',81),
  ('conjunction -> LPAREN formula CONJUNCTION formula RPAREN','conjunction',5,'p_conjunction','odgarbacza.py',88),
  ('equivalence -> LPAREN formula EQUIVALENCE formula RPAREN','equivalence',5,'p_equivalence','odgarbacza.py',97),
]
